/* NEXT */
import type { Metadata } from "next";
import { Inter } from "next/font/google";

/* NAVBAR */
import Navbar from "@/components/shared/Navbar";

/** Redux */
import { Providers } from "@/redux/provider";

/** CSS */
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
